{"name": "Логин с неверным email", "status": "passed", "start": 1741874042169, "stop": 1741874042412, "uuid": "47f3aa15-8e3e-45a3-9159-88649471bdc0", "historyId": "80532f8e7bee1082516926711d9bfeb0", "testCaseId": "80532f8e7bee1082516926711d9bfeb0", "fullName": "tests.test_user_login.TestUserLogin#test_login_invalid_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "Pro_Fortis_M"}, {"name": "thread", "value": "25340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}